// 단어 DB — photos/ 폴더의 교재 사진에서 OCR로 추출
// day17: 25개, day18: 29개
const WORDS = [
  // ─── DAY 17 (25) ───
  { day: 17, num: 1,  word: "relate",      meaning: "관련짓다; 관련이 있다" },
  { day: 17, num: 2,  word: "correlation", meaning: "연관성, 상호 관련" },
  { day: 17, num: 3,  word: "translate",   meaning: "번역하다, 해석하다" },
  { day: 17, num: 4,  word: "congestion",  meaning: "(교통) 혼잡, (인구) 밀집" },
  { day: 17, num: 5,  word: "digest",      meaning: "소화시키다; 요약(문)" },
  { day: 17, num: 6,  word: "register",    meaning: "등록하다, 신고하다; 등록부" },
  { day: 17, num: 7,  word: "exaggerate",  meaning: "과장하다, 지나치게 강조하다" },
  { day: 17, num: 8,  word: "prefer",      meaning: "더 좋아하다, 선호하다, 차라리 ~을 택하다" },
  { day: 17, num: 9,  word: "refer",       meaning: "참고하다, 언급하다, 인용하다" },
  { day: 17, num: 10, word: "conference",  meaning: "회의, 회담, 학회" },
  { day: 17, num: 11, word: "differ",      meaning: "다르다, 의견을 달리하다" },
  { day: 17, num: 12, word: "indifferent", meaning: "무관심한, 무관한" },
  { day: 17, num: 13, word: "infer",       meaning: "추론하다, 암시하다" },
  { day: 17, num: 14, word: "fertile",     meaning: "비옥한, 다산의" },
  { day: 17, num: 15, word: "ferry",       meaning: "(사람, 화물 운반용의) 연락선; 나르다, 수송하다" },
  { day: 17, num: 16, word: "defer",       meaning: "미루다, 연기하다, 경의를 표하다" },
  { day: 17, num: 17, word: "cast",        meaning: "던지다, (그림자를) 드리우다; 던지기" },
  { day: 17, num: 18, word: "broadcast",   meaning: "방송하다, 방영하다; 방송" },
  { day: 17, num: 19, word: "outcast",     meaning: "버림받은, 쫓겨난; 버림받은 사람, 따돌려진 사람" },
  { day: 17, num: 20, word: "object",      meaning: "물건, 대상, 목표; 반대하다" },
  { day: 17, num: 21, word: "subject",     meaning: "지배하에 두다; ~의 지배하에 있는; 과목, 주제, (연구) 대상, 백성/신하" },
  { day: 17, num: 22, word: "project",     meaning: "(연구) 과제, 사업; 계획하다, 투사하다" },
  { day: 17, num: 23, word: "reject",      meaning: "거절하다, 거부하다, 부인하다" },
  { day: 17, num: 24, word: "inject",      meaning: "주사하다, 주입하다" },
  { day: 17, num: 25, word: "eject",       meaning: "튀어나오게 하다, 쫓아내다" },
  // ─── DAY 18 (29) ───
  { day: 18, num: 1,  word: "attract",     meaning: "(관심 등을) 끌다, 끌어모으다" },
  { day: 18, num: 2,  word: "contract",    meaning: "계약하다, 수축하다; 계약(서)" },
  { day: 18, num: 3,  word: "distract",    meaning: "(주의를) 산만하게 하다" },
  { day: 18, num: 4,  word: "abstract",    meaning: "추출하다, 끌어내다; 추상적인; 추상 (개념)" },
  { day: 18, num: 5,  word: "extract",     meaning: "추출하다, 발췌하다; 추출물, 발췌" },
  { day: 18, num: 6,  word: "subtract",    meaning: "빼다, 덜다" },
  { day: 18, num: 7,  word: "track",       meaning: "(지나다녀서 생긴) 길, 선로, 경주로; 추적하다" },
  { day: 18, num: 8,  word: "trace",       meaning: "자취, 흔적; 추적하다, 따라가다" },
  { day: 18, num: 9,  word: "trade",       meaning: "거래, 무역; 거래하다, 교역하다" },
  { day: 18, num: 10, word: "trail",       meaning: "자국, 시골길, (특정한) 코스; 뒤쫓다" },
  { day: 18, num: 11, word: "trait",       meaning: "특성, 특징" },
  { day: 18, num: 12, word: "portray",     meaning: "묘사하다, 그리다, 보여주다" },
  { day: 18, num: 13, word: "treat",       meaning: "대(접)하다, 다루다, 치료하다; 대접" },
  { day: 18, num: 14, word: "retreat",     meaning: "후퇴하다, 물러나다; 후퇴, 철수, (일상에서 물러나서 가는) 휴양 시설" },
  { day: 18, num: 15, word: "treaty",      meaning: "조약, 협정" },
  { day: 18, num: 16, word: "produce",     meaning: "생산하다, 제작하다" },
  { day: 18, num: 17, word: "reproduce",   meaning: "재생하다, 번식하다, 복사하다" },
  { day: 18, num: 18, word: "reduce",      meaning: "줄이다, 감소하다" },
  { day: 18, num: 19, word: "education",   meaning: "교육 (기관), 교육학" },
  { day: 18, num: 20, word: "conduct",     meaning: "이끌다, 지휘하다, 실시하다; 지도, 행위, 품행" },
  { day: 18, num: 21, word: "induce",      meaning: "유도하다, 유발하다, 설득하다" },
  { day: 18, num: 22, word: "deduce",      meaning: "추론하다, 연역하다" },
  { day: 18, num: 23, word: "compel",      meaning: "강요하다, 억지로 ~하게 하다" },
  { day: 18, num: 24, word: "propel",      meaning: "나아가게 하다, 추진하다" },
  { day: 18, num: 25, word: "expel",       meaning: "쫓아내다, 추방하다, 배출하다" },
  { day: 18, num: 26, word: "repel",       meaning: "쫓아버리다, 물리치다" },
  { day: 18, num: 27, word: "appeal",      meaning: "관심을 끌다, 호소하다; 호소, 매력" },
  { day: 18, num: 28, word: "pulse",       meaning: "맥박, 진동, 파동; 맥박치다" },
  { day: 18, num: 29, word: "impulsive",   meaning: "충동적인, 행동을 자극하는" },
];
