INSERT INTO words (day, num, word, meaning) VALUES (17, 1, 'relate', '관련짓다; 관련이 있다') ON CONFLICT(word) DO UPDATE SET day=17, num=1, meaning='관련짓다; 관련이 있다';
INSERT INTO words (day, num, word, meaning) VALUES (17, 2, 'correlation', '연관성, 상호 관련') ON CONFLICT(word) DO UPDATE SET day=17, num=2, meaning='연관성, 상호 관련';
INSERT INTO words (day, num, word, meaning) VALUES (17, 3, 'translate', '번역하다, 해석하다') ON CONFLICT(word) DO UPDATE SET day=17, num=3, meaning='번역하다, 해석하다';
INSERT INTO words (day, num, word, meaning) VALUES (17, 4, 'congestion', '(교통) 혼잡, (인구) 밀집') ON CONFLICT(word) DO UPDATE SET day=17, num=4, meaning='(교통) 혼잡, (인구) 밀집';
INSERT INTO words (day, num, word, meaning) VALUES (17, 5, 'digest', '소화시키다; 요약(문)') ON CONFLICT(word) DO UPDATE SET day=17, num=5, meaning='소화시키다; 요약(문)';
INSERT INTO words (day, num, word, meaning) VALUES (17, 6, 'register', '등록하다, 신고하다; 등록부') ON CONFLICT(word) DO UPDATE SET day=17, num=6, meaning='등록하다, 신고하다; 등록부';
INSERT INTO words (day, num, word, meaning) VALUES (17, 7, 'exaggerate', '과장하다, 지나치게 강조하다') ON CONFLICT(word) DO UPDATE SET day=17, num=7, meaning='과장하다, 지나치게 강조하다';
INSERT INTO words (day, num, word, meaning) VALUES (17, 8, 'prefer', '더 좋아하다, 선호하다, 차라리 ~을 택하다') ON CONFLICT(word) DO UPDATE SET day=17, num=8, meaning='더 좋아하다, 선호하다, 차라리 ~을 택하다';
INSERT INTO words (day, num, word, meaning) VALUES (17, 9, 'refer', '참고하다, 언급하다, 인용하다') ON CONFLICT(word) DO UPDATE SET day=17, num=9, meaning='참고하다, 언급하다, 인용하다';
INSERT INTO words (day, num, word, meaning) VALUES (17, 10, 'conference', '회의, 회담, 학회') ON CONFLICT(word) DO UPDATE SET day=17, num=10, meaning='회의, 회담, 학회';
INSERT INTO words (day, num, word, meaning) VALUES (17, 11, 'differ', '다르다, 의견을 달리하다') ON CONFLICT(word) DO UPDATE SET day=17, num=11, meaning='다르다, 의견을 달리하다';
INSERT INTO words (day, num, word, meaning) VALUES (17, 12, 'indifferent', '무관심한, 무관한') ON CONFLICT(word) DO UPDATE SET day=17, num=12, meaning='무관심한, 무관한';
INSERT INTO words (day, num, word, meaning) VALUES (17, 13, 'infer', '추론하다, 암시하다') ON CONFLICT(word) DO UPDATE SET day=17, num=13, meaning='추론하다, 암시하다';
INSERT INTO words (day, num, word, meaning) VALUES (17, 14, 'fertile', '비옥한, 다산의') ON CONFLICT(word) DO UPDATE SET day=17, num=14, meaning='비옥한, 다산의';
INSERT INTO words (day, num, word, meaning) VALUES (17, 15, 'ferry', '(사람, 화물 운반용의) 연락선; 나르다, 수송하다') ON CONFLICT(word) DO UPDATE SET day=17, num=15, meaning='(사람, 화물 운반용의) 연락선; 나르다, 수송하다';
INSERT INTO words (day, num, word, meaning) VALUES (17, 16, 'defer', '미루다, 연기하다, 경의를 표하다') ON CONFLICT(word) DO UPDATE SET day=17, num=16, meaning='미루다, 연기하다, 경의를 표하다';
INSERT INTO words (day, num, word, meaning) VALUES (17, 17, 'cast', '던지다, (그림자를) 드리우다; 던지기') ON CONFLICT(word) DO UPDATE SET day=17, num=17, meaning='던지다, (그림자를) 드리우다; 던지기';
INSERT INTO words (day, num, word, meaning) VALUES (17, 18, 'broadcast', '방송하다, 방영하다; 방송') ON CONFLICT(word) DO UPDATE SET day=17, num=18, meaning='방송하다, 방영하다; 방송';
INSERT INTO words (day, num, word, meaning) VALUES (17, 19, 'outcast', '버림받은, 쫓겨난; 버림받은 사람, 따돌려진 사람') ON CONFLICT(word) DO UPDATE SET day=17, num=19, meaning='버림받은, 쫓겨난; 버림받은 사람, 따돌려진 사람';
INSERT INTO words (day, num, word, meaning) VALUES (17, 20, 'object', '물건, 대상, 목표; 반대하다') ON CONFLICT(word) DO UPDATE SET day=17, num=20, meaning='물건, 대상, 목표; 반대하다';
INSERT INTO words (day, num, word, meaning) VALUES (17, 21, 'subject', '지배하에 두다; ~의 지배하에 있는; 과목, 주제, (연구) 대상, 백성/신하') ON CONFLICT(word) DO UPDATE SET day=17, num=21, meaning='지배하에 두다; ~의 지배하에 있는; 과목, 주제, (연구) 대상, 백성/신하';
INSERT INTO words (day, num, word, meaning) VALUES (17, 22, 'project', '(연구) 과제, 사업; 계획하다, 투사하다') ON CONFLICT(word) DO UPDATE SET day=17, num=22, meaning='(연구) 과제, 사업; 계획하다, 투사하다';
INSERT INTO words (day, num, word, meaning) VALUES (17, 23, 'reject', '거절하다, 거부하다, 부인하다') ON CONFLICT(word) DO UPDATE SET day=17, num=23, meaning='거절하다, 거부하다, 부인하다';
INSERT INTO words (day, num, word, meaning) VALUES (17, 24, 'inject', '주사하다, 주입하다') ON CONFLICT(word) DO UPDATE SET day=17, num=24, meaning='주사하다, 주입하다';
INSERT INTO words (day, num, word, meaning) VALUES (17, 25, 'eject', '튀어나오게 하다, 쫓아내다') ON CONFLICT(word) DO UPDATE SET day=17, num=25, meaning='튀어나오게 하다, 쫓아내다';
INSERT INTO words (day, num, word, meaning) VALUES (18, 1, 'attract', '(관심 등을) 끌다, 끌어모으다') ON CONFLICT(word) DO UPDATE SET day=18, num=1, meaning='(관심 등을) 끌다, 끌어모으다';
INSERT INTO words (day, num, word, meaning) VALUES (18, 2, 'contract', '계약하다, 수축하다; 계약(서)') ON CONFLICT(word) DO UPDATE SET day=18, num=2, meaning='계약하다, 수축하다; 계약(서)';
INSERT INTO words (day, num, word, meaning) VALUES (18, 3, 'distract', '(주의를) 산만하게 하다') ON CONFLICT(word) DO UPDATE SET day=18, num=3, meaning='(주의를) 산만하게 하다';
INSERT INTO words (day, num, word, meaning) VALUES (18, 4, 'abstract', '추출하다, 끌어내다; 추상적인; 추상 (개념)') ON CONFLICT(word) DO UPDATE SET day=18, num=4, meaning='추출하다, 끌어내다; 추상적인; 추상 (개념)';
INSERT INTO words (day, num, word, meaning) VALUES (18, 5, 'extract', '추출하다, 발췌하다; 추출물, 발췌') ON CONFLICT(word) DO UPDATE SET day=18, num=5, meaning='추출하다, 발췌하다; 추출물, 발췌';
INSERT INTO words (day, num, word, meaning) VALUES (18, 6, 'subtract', '빼다, 덜다') ON CONFLICT(word) DO UPDATE SET day=18, num=6, meaning='빼다, 덜다';
INSERT INTO words (day, num, word, meaning) VALUES (18, 7, 'track', '(지나다녀서 생긴) 길, 선로, 경주로; 추적하다') ON CONFLICT(word) DO UPDATE SET day=18, num=7, meaning='(지나다녀서 생긴) 길, 선로, 경주로; 추적하다';
INSERT INTO words (day, num, word, meaning) VALUES (18, 8, 'trace', '자취, 흔적; 추적하다, 따라가다') ON CONFLICT(word) DO UPDATE SET day=18, num=8, meaning='자취, 흔적; 추적하다, 따라가다';
INSERT INTO words (day, num, word, meaning) VALUES (18, 9, 'trade', '거래, 무역; 거래하다, 교역하다') ON CONFLICT(word) DO UPDATE SET day=18, num=9, meaning='거래, 무역; 거래하다, 교역하다';
INSERT INTO words (day, num, word, meaning) VALUES (18, 10, 'trail', '자국, 시골길, (특정한) 코스; 뒤쫓다') ON CONFLICT(word) DO UPDATE SET day=18, num=10, meaning='자국, 시골길, (특정한) 코스; 뒤쫓다';
INSERT INTO words (day, num, word, meaning) VALUES (18, 11, 'trait', '특성, 특징') ON CONFLICT(word) DO UPDATE SET day=18, num=11, meaning='특성, 특징';
INSERT INTO words (day, num, word, meaning) VALUES (18, 12, 'portray', '묘사하다, 그리다, 보여주다') ON CONFLICT(word) DO UPDATE SET day=18, num=12, meaning='묘사하다, 그리다, 보여주다';
INSERT INTO words (day, num, word, meaning) VALUES (18, 13, 'treat', '대(접)하다, 다루다, 치료하다; 대접') ON CONFLICT(word) DO UPDATE SET day=18, num=13, meaning='대(접)하다, 다루다, 치료하다; 대접';
INSERT INTO words (day, num, word, meaning) VALUES (18, 14, 'retreat', '후퇴하다, 물러나다; 후퇴, 철수, (일상에서 물러나서 가는) 휴양 시설') ON CONFLICT(word) DO UPDATE SET day=18, num=14, meaning='후퇴하다, 물러나다; 후퇴, 철수, (일상에서 물러나서 가는) 휴양 시설';
INSERT INTO words (day, num, word, meaning) VALUES (18, 15, 'treaty', '조약, 협정') ON CONFLICT(word) DO UPDATE SET day=18, num=15, meaning='조약, 협정';
INSERT INTO words (day, num, word, meaning) VALUES (18, 16, 'produce', '생산하다, 제작하다') ON CONFLICT(word) DO UPDATE SET day=18, num=16, meaning='생산하다, 제작하다';
INSERT INTO words (day, num, word, meaning) VALUES (18, 17, 'reproduce', '재생하다, 번식하다, 복사하다') ON CONFLICT(word) DO UPDATE SET day=18, num=17, meaning='재생하다, 번식하다, 복사하다';
INSERT INTO words (day, num, word, meaning) VALUES (18, 18, 'reduce', '줄이다, 감소하다') ON CONFLICT(word) DO UPDATE SET day=18, num=18, meaning='줄이다, 감소하다';
INSERT INTO words (day, num, word, meaning) VALUES (18, 19, 'education', '교육 (기관), 교육학') ON CONFLICT(word) DO UPDATE SET day=18, num=19, meaning='교육 (기관), 교육학';
INSERT INTO words (day, num, word, meaning) VALUES (18, 20, 'conduct', '이끌다, 지휘하다, 실시하다; 지도, 행위, 품행') ON CONFLICT(word) DO UPDATE SET day=18, num=20, meaning='이끌다, 지휘하다, 실시하다; 지도, 행위, 품행';
INSERT INTO words (day, num, word, meaning) VALUES (18, 21, 'induce', '유도하다, 유발하다, 설득하다') ON CONFLICT(word) DO UPDATE SET day=18, num=21, meaning='유도하다, 유발하다, 설득하다';
INSERT INTO words (day, num, word, meaning) VALUES (18, 22, 'deduce', '추론하다, 연역하다') ON CONFLICT(word) DO UPDATE SET day=18, num=22, meaning='추론하다, 연역하다';
INSERT INTO words (day, num, word, meaning) VALUES (18, 23, 'compel', '강요하다, 억지로 ~하게 하다') ON CONFLICT(word) DO UPDATE SET day=18, num=23, meaning='강요하다, 억지로 ~하게 하다';
INSERT INTO words (day, num, word, meaning) VALUES (18, 24, 'propel', '나아가게 하다, 추진하다') ON CONFLICT(word) DO UPDATE SET day=18, num=24, meaning='나아가게 하다, 추진하다';
INSERT INTO words (day, num, word, meaning) VALUES (18, 25, 'expel', '쫓아내다, 추방하다, 배출하다') ON CONFLICT(word) DO UPDATE SET day=18, num=25, meaning='쫓아내다, 추방하다, 배출하다';
INSERT INTO words (day, num, word, meaning) VALUES (18, 26, 'repel', '쫓아버리다, 물리치다') ON CONFLICT(word) DO UPDATE SET day=18, num=26, meaning='쫓아버리다, 물리치다';
INSERT INTO words (day, num, word, meaning) VALUES (18, 27, 'appeal', '관심을 끌다, 호소하다; 호소, 매력') ON CONFLICT(word) DO UPDATE SET day=18, num=27, meaning='관심을 끌다, 호소하다; 호소, 매력';
INSERT INTO words (day, num, word, meaning) VALUES (18, 28, 'pulse', '맥박, 진동, 파동; 맥박치다') ON CONFLICT(word) DO UPDATE SET day=18, num=28, meaning='맥박, 진동, 파동; 맥박치다';
INSERT INTO words (day, num, word, meaning) VALUES (18, 29, 'impulsive', '충동적인, 행동을 자극하는') ON CONFLICT(word) DO UPDATE SET day=18, num=29, meaning='충동적인, 행동을 자극하는';
